# Generated by Django 5.1.1 on 2024-10-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('phone', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('opening_amount', models.IntegerField(db_column='Balance')),
            ],
        ),
    ]
