# Generated by Django 5.1.1 on 2024-10-07 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('type', models.CharField(choices=[('deposit', 'DEPOSIT'), ('withdraw', 'WITHDRAW'), ('transfer', 'TRANSFER')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='customer.customer')),
                ('customer_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer_to', to='customer.customer')),
            ],
        ),
    ]
